/* Blue Passage — self-contained arcade voyage. Geographic layout is deliberately stylized. */
'use strict';
const $=id=>document.getElementById(id),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const scene=new THREE.Scene();scene.background=new THREE.Color('#83bfc7');scene.fog=new THREE.FogExp2('#83bfc7',.0025);
const camera=new THREE.PerspectiveCamera(52,innerWidth/innerHeight,.5,2400);
let renderer;try{renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});}catch(e){$('intro').textContent='WebGL is unavailable. Enable hardware acceleration in your browser and reopen this file.';throw e;}
renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.outputColorSpace=THREE.SRGBColorSpace;document.body.prepend(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xc6f6ff,0x7d6453,2.3));const sun=new THREE.DirectionalLight(0xffe8c4,3);sun.position.set(-180,350,100);scene.add(sun);
const mat=(c,extra={})=>new THREE.MeshStandardMaterial({color:c,roughness:.8,...extra});
const sand=mat('#c6ae81'),rock=mat('#9d8c70'),dark=mat('#233d48'),white=mat('#e1eee7'),red=mat('#ed7951'),mint=mat('#94ffd3',{emissive:'#3da880',emissiveIntensity:.5});
function mesh(g,m,x=0,y=0,z=0,parent=scene){const o=new THREE.Mesh(g,m);o.position.set(x,y,z);parent.add(o);return o;}
function box(w,h,d,m,x,y,z,p){return mesh(new THREE.BoxGeometry(w,h,d),m,x,y,z,p);}
const waterGeo=new THREE.PlaneGeometry(2600,2300,160,145);waterGeo.rotateX(-Math.PI/2);const water=mesh(waterGeo,mat('#187b91',{metalness:.35,roughness:.34}));const wp=waterGeo.attributes.position;
// World axes: east = +X, north = -Z. A compressed navigable corridor preserves the voyage sequence.
const routeBase=[new THREE.Vector3(600,0,320),new THREE.Vector3(440,0,290),new THREE.Vector3(260,0,200),new THREE.Vector3(100,0,95),new THREE.Vector3(-25,0,10),new THREE.Vector3(-85,0,-95),new THREE.Vector3(-230,0,-175),new THREE.Vector3(-400,0,-285),new THREE.Vector3(-550,0,-380)];
const volcanoSites=[{name:'CINDER KEY',x:-170,z:-135,rx:23,rz:18,height:58},{name:'EMBER ATOLL',x:330,z:330,rx:30,rz:24,height:82}];
function makeIslandCoast(site,index){return Array.from({length:14},(_,i)=>{const a=i/14*Math.PI*2,wobble=.88+.1*Math.sin(i*1.7+index)+.04*Math.cos(i*2.3-index);return[site.x+Math.cos(a)*site.rx*wobble,site.z+Math.sin(a)*site.rz*wobble];});}
const lands=[{name:'IRAN',p:[[-620,-490],[-520,-440],[-390,-340],[-250,-235],[-105,-150],[-38,-98],[35,-35],[170,5],[330,20],[510,0],[700,-45],[740,-580]]},{name:'ARABIA',p:[[-650,-365],[-540,-320],[-430,-235],[-270,-130],[-150,-40],[-130,35],[-20,125],[80,220],[50,355],[-260,560],[-760,520]]},{name:'INDIA',p:[[720,-80],[660,90],[670,205],[710,290],[690,420],[820,670],[1010,620],[1010,-110]]},...volcanoSites.map((site,i)=>({name:site.name,volcanic:true,p:makeIslandCoast(site,i)}))];
function landShape(poly){const s=new THREE.Shape();poly.forEach(([x,z],i)=>i?s.lineTo(x,-z):s.moveTo(x,-z));s.closePath();const g=new THREE.ExtrudeGeometry(s,{depth:13,bevelEnabled:true,bevelSize:9,bevelThickness:5,bevelSegments:1,steps:1});g.rotateX(-Math.PI/2);mesh(g,sand,0,-6,0);const cx=poly.reduce((a,p)=>a+p[0],0)/poly.length,cz=poly.reduce((a,p)=>a+p[1],0)/poly.length;const coastTop=poly.map(([x,z])=>new THREE.Vector3(x,7.12,z));const foam=poly.map(([x,z])=>{const dx=x-cx,dz=z-cz,d=Math.hypot(dx,dz)||1;return new THREE.Vector3(x+dx/d*7,1.45,z+dz/d*7);});const lip=new THREE.LineLoop(new THREE.BufferGeometry().setFromPoints(coastTop),new THREE.LineBasicMaterial({color:'#f2dfb8',transparent:true,opacity:.72,depthTest:false}));lip.renderOrder=5;scene.add(lip);const surf=new THREE.LineLoop(new THREE.BufferGeometry().setFromPoints(foam),new THREE.LineBasicMaterial({color:'#a4f0de',transparent:true,opacity:.58,depthTest:false}));surf.renderOrder=5;scene.add(surf);}
lands.forEach(l=>landShape(l.p));
function inside(x,z,p){let c=false;for(let i=0,j=p.length-1;i<p.length;j=i++){const a=p[i],b=p[j];if((a[1]>z)!=(b[1]>z)&&x<(b[0]-a[0])*(z-a[1])/(b[1]-a[1])+a[0])c=!c;}return c;}
let seed=42;function rand(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;}
for(let i=0;i<290;i++){let x=rand()*1700-750,z=rand()*1080-540;if(lands.some(l=>!l.volcanic&&inside(x,z,l.p))){let h=15+rand()*65;const m=mesh(new THREE.ConeGeometry(15+rand()*30,h,5),i%3?rock:sand,x,h/2+8,z);m.rotation.y=rand()*6;}}
function label(text,x,z,size=23,y=45){const c=document.createElement('canvas');c.width=512;c.height=80;const ctx=c.getContext('2d');ctx.font='500 30px Arial';ctx.textAlign='center';ctx.fillStyle='#ecf9ed';ctx.fillText(text,256,47);const t=new THREE.CanvasTexture(c),sp=new THREE.Sprite(new THREE.SpriteMaterial({map:t,transparent:true,depthTest:false,opacity:.8}));sp.position.set(x,y,z);sp.scale.set(size*7,size,1);scene.add(sp);}
label('IRAN',-40,-290);label('OMAN',-40,265);label('INDIA',820,190);label('PAKISTAN',530,-80);label('IRAQ',-570,-455);label('PERSIAN GULF',-320,-190,16);label('STRAIT OF HORMUZ',-62,-65,12);label('SEA OF OMAN',190,130,17);label('INDIAN OCEAN',480,450,19);
const volcanoes=[];function makeVolcano(site,index){const group=new THREE.Group();group.position.set(site.x,7,site.z);scene.add(group);const cone=mesh(new THREE.ConeGeometry(site.rx*.72,site.height,18,5),mat('#34363a',{roughness:.97}),0,site.height/2,0,group);cone.rotation.y=index*.42;const craterMat=new THREE.MeshBasicMaterial({color:'#ff642c',transparent:true,opacity:.86,side:THREE.DoubleSide});const crater=mesh(new THREE.CircleGeometry(site.rx*.17,28),craterMat,0,site.height*.91,0,group);crater.rotation.x=-Math.PI/2;const rim=mesh(new THREE.TorusGeometry(site.rx*.18,1.3,7,28),new THREE.MeshBasicMaterial({color:'#ff8950',transparent:true,opacity:.9}),0,site.height*.91,0,group);rim.rotation.x=Math.PI/2;const flows=[];for(let j=0;j<3;j++){const points=[];for(let k=0;k<=22;k++){const u=k/22,r=site.rx*.72*(.08+.82*u),a=j*Math.PI*2/3+Math.sin(u*8+j)*.045,y=site.height*(.94-.88*u)+.8;points.push(new THREE.Vector3(Math.cos(a)*r,y,Math.sin(a)*r));}const material=new THREE.LineBasicMaterial({color:j===1?'#ffad52':'#ff5c34',transparent:true,opacity:.88});const flow=new THREE.Line(new THREE.BufferGeometry().setFromPoints(points),material);group.add(flow);flows.push(flow);}const puffs=[];for(let j=0;j<4;j++){const material=new THREE.MeshBasicMaterial({color:j<2?'#505358':'#666365',transparent:true,opacity:.27,depthWrite:false});const puff=mesh(new THREE.SphereGeometry(7+j*2.4,9,7),material,Math.sin(j*2)*3,site.height+12+j*12,Math.cos(j*2)*3,group);puff.scale.set(1.25,.9,1);puffs.push(puff);}const light=new THREE.PointLight('#ff6b38',3.1,125,2);light.position.set(0,site.height*.8,0);group.add(light);label(site.name,site.x,site.z,10,site.height+92);return{group,site,craterMat,flows,puffs,light,phase:index*1.8};}volcanoSites.forEach((site,i)=>volcanoes.push(makeVolcano(site,i)));
function vessel(navy=false){const g=new THREE.Group(),hull=mesh(new THREE.CylinderGeometry(navy?7:4,navy?5:3,navy?34:17,5),navy?dark:red,0,3,0,g);hull.rotation.x=Math.PI/2;box(navy?11:7,2,navy?27:13,navy?dark:white,0,5,0,g);box(navy?7:5,navy?8:4,navy?10:5,white,0,navy?9:8,3,g);box(navy?5:4,1,2,mat('#284d60'),0,navy?11:9,navy?-2:0,g);box(.5,navy?16:8,.5,dark,0,navy?17:13,4,g);if(!navy){box(3,2.5,4,mint,0,7,-4,g);}else{box(3,2,6,dark,0,7,-10,g);}scene.add(g);return g;}
const player=vessel();const navy=[];for(let i=0;i<3;i++){const ship=vessel(true);navy.push({mesh:ship,x:75+i*90,z:120+i*48,phase:i*2});}
const aircraft=[];for(let i=0;i<4;i++){const g=new THREE.Group();box(2,1,10,white,0,0,0,g);box(13,.4,3,white,0,0,1,g);box(5,.5,2,dark,0,1,4,g);scene.add(g);aircraft.push(g);}
const beacons=routeBase.map(p=>{const g=new THREE.Group();mesh(new THREE.TorusGeometry(11,.8,6,32),mint,0,12,0,g);box(1,12,1,mint,0,5,0,g);g.position.copy(p);scene.add(g);return g;});
const repairs=[];for(let i=1;i<8;i++){const p=routeBase[i].clone();p.x+=i%2?18:-18;const o=box(7,7,7,mint,p.x,5,p.z);box(8,1.5,2,white,0,0,0,o);box(2,1.5,8,white,0,0,0,o);repairs.push(o);}
const wakes=[];for(let i=0;i<24;i++){const w=mesh(new THREE.RingGeometry(2,3.3,16),new THREE.MeshBasicMaterial({color:0xc1fff0,transparent:true,opacity:0,side:THREE.DoubleSide}));w.rotation.x=-Math.PI/2;w.visible=false;wakes.push(w);}let wakeClock=0,wakeIndex=0;
const hazards=[],effects=[];const mineMat=mat('#26323a'),danger=mat('#ff8156',{emissive:'#b83713',emissiveIntensity:.8});
function removeAt(arr,i){scene.remove(arr[i].mesh);arr[i].mesh.traverse(o=>{if(o.geometry)o.geometry.dispose();});arr.splice(i,1);}
const burstMaterials=new Map([[0xffab60,danger]]);function burst(x,z,color=0xffab60){let material=burstMaterials.get(color);if(!material){material=new THREE.MeshBasicMaterial({color,transparent:true,opacity:.96});burstMaterials.set(color,material);}for(let i=0;i<10;i++){const o=mesh(new THREE.IcosahedronGeometry(1.6,0),material,x,3,z);effects.push({mesh:o,v:new THREE.Vector3((Math.random()-.5)*30,10+Math.random()*20,(Math.random()-.5)*30),life:1});}}
function spawn(type,x,z){let o,ring;if(type==='mine'){o=new THREE.Group();mesh(new THREE.IcosahedronGeometry(3.5,1),mineMat,0,1,0,o);for(let i=0;i<6;i++){const a=i*Math.PI/3;box(1,1,2,danger,Math.sin(a)*3.4,1,Math.cos(a)*3.4,o);}scene.add(o);}else{o=new THREE.Group();ring=mesh(new THREE.TorusGeometry(type==='rocket'?10:7,.45,6,32),danger,0,.5,0,o);ring.rotation.x=Math.PI/2;const b=mesh(type==='rocket'?new THREE.ConeGeometry(1.8,9,6):new THREE.OctahedronGeometry(3),danger,0,60,0,o);if(type==='drone')box(11,.5,2,dark,0,60,0,o);scene.add(o);}o.position.set(x,0,z);hazards.push({mesh:o,type,age:0,life:type==='mine'?35:3.4,ring});}
const towerMetal=mat('#3c5961',{metalness:.42,roughness:.55}),towerGlow=new THREE.MeshBasicMaterial({color:'#82f4ee'});
function makeCoastTower(site,index){const group=new THREE.Group();group.position.set(site.x,7.15,site.z);scene.add(group);mesh(new THREE.CylinderGeometry(5.2,6.5,3,10),dark,0,1.5,0,group);mesh(new THREE.CylinderGeometry(2.6,3.4,12,10),towerMetal,0,8.5,0,group);mesh(new THREE.CylinderGeometry(5.2,5.6,2,10),dark,0,14.5,0,group);const head=new THREE.Group();head.position.set(0,15.8,0);head.rotation.y=site.seaYaw;group.add(head);mesh(new THREE.CylinderGeometry(2.8,3.2,2.8,10),towerMetal,0,.4,0,head);const barrel=mesh(new THREE.BoxGeometry(9,1.1,1.5),dark,-4,.75,0,head);mesh(new THREE.SphereGeometry(1,8,6),towerGlow,0,1.7,.7,head);const rail=mesh(new THREE.TorusGeometry(4.7,.22,6,24),towerGlow,0,15.9,0,group);rail.rotation.x=Math.PI/2;const lamp=new THREE.PointLight('#6bdedc',1.6,48,2);lamp.position.set(0,18,0);group.add(lamp);return{group,head,barrel,lamp,site,phase:index*.9,cooldown:.4+index*.28,range:205};}
const coastTowerSites=[{x:-500,z:-440,seaYaw:Math.PI/2},{x:-210,z:-225,seaYaw:Math.PI/2},{x:-72,z:-130,seaYaw:Math.PI/2},{x:122,z:-30,seaYaw:Math.PI/2},{x:360,z:-27,seaYaw:Math.PI/2},{x:-135,z:35,seaYaw:-Math.PI/2},{x:10,z:180,seaYaw:-Math.PI/2},{x:-90,z:335,seaYaw:-Math.PI/2}];
const coastTowers=coastTowerSites.filter(s=>lands.some(l=>!l.volcanic&&inside(s.x,s.z,l.p))).map(makeCoastTower),defenseShots=[];
function fireCoastTower(tower,hazard){const target=hazard.mesh.position.clone().add(new THREE.Vector3(0,hazard.type==='mine'?1:34,0));tower.head.rotation.y=Math.atan2(target.z-tower.group.position.z,-(target.x-tower.group.position.x));tower.group.updateMatrixWorld(true);const muzzle=tower.head.localToWorld(new THREE.Vector3(-8,.1,0));const beam=new THREE.Line(new THREE.BufferGeometry().setFromPoints([muzzle,target]),new THREE.LineBasicMaterial({color:'#9bf7f1',transparent:true,opacity:.96,depthTest:false}));scene.add(beam);defenseShots.push({mesh:beam,life:.24});}
let route=routeBase,leg=1,hp=100,boost=100,throttle=.65,speed=0,heading=0,time=0,t=0,spawnClock=0,patrolClock=0,invulnerable=0,running=false,paused=false,easy=false,camMode=0,shake=0;
const keys={};function clearKeys(){Object.keys(keys).forEach(k=>keys[k]=false);}addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();keys[e.key.toLowerCase()]=true;if(!e.repeat&&e.key.toLowerCase()==='p')togglePause();if(!e.repeat&&e.key.toLowerCase()==='c')camMode=(camMode+1)%2;});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);addEventListener('blur',()=>{clearKeys();if(running&&!paused)togglePause();});
document.querySelectorAll('[data-key]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys[b.dataset.key]=true;};b.onpointerup=b.onpointercancel=()=>keys[b.dataset.key]=false;});
function togglePause(){if(!running)return;paused=!paused;$('pause').textContent=paused?'Resume · P':'Pause · P';$('alert').textContent=paused?'VOYAGE PAUSED':'';clearKeys();}$('pause').onclick=togglePause;$('easy').onclick=()=>{easy=!easy;$('easy').textContent='Mode: '+(easy?'Explorer':'Standard');};
function start(){route=$('direction').value==='1'?[...routeBase].reverse():[...routeBase];leg=1;player.position.copy(route[0]);heading=Math.atan2(-(route[1].x-route[0].x),-(route[1].z-route[0].z));hp=100;boost=100;throttle=.65;speed=0;time=0;invulnerable=0;spawnClock=0;patrolClock=0;running=true;paused=false;clearKeys();hazards.forEach(h=>scene.remove(h.mesh));hazards.length=0;repairs.forEach(r=>r.visible=true);$('overlay').style.display='none';$('pause').textContent='Pause · P';$('alert').textContent='';}
$('start').onclick=start;
function finish(win){running=false;$('overlay').style.display='flex';document.querySelector('h1').innerHTML=win?'PASSAGE<br>COMPLETE.':'LOST<br>AT SEA.';$('intro').textContent=win?`Safe arrival with ${Math.floor(hp)}% hull in ${Math.floor(time/60)}m ${Math.floor(time%60)}s. Try the return voyage or beat your time.`:'Your hull reached 0%. Steer away from orange target rings, collect green repair crates, and save boost for the narrow strait.';$('start').textContent='Sail again ↗';}
function damage(amount,msg){if(invulnerable>0)return;hp=Math.max(0,hp-amount*(easy?.55:1));invulnerable=1.25;shake=.6;$('alert').textContent=msg;burst(player.position.x,player.position.z);if(hp<1)finish(false);}
const mapctx=$('map').getContext('2d');function minimap(){const c=mapctx;c.clearRect(0,0,280,210);const mx=x=>20+(x+650)/1500*245,mz=z=>22+(z+480)/1080*165;c.fillStyle='#789586';lands.forEach(l=>{c.beginPath();l.p.forEach(([x,z],i)=>i?c.lineTo(mx(x),mz(z)):c.moveTo(mx(x),mz(z)));c.closePath();c.fill();});c.strokeStyle='#70dac080';c.setLineDash([3,4]);c.beginPath();route.forEach((p,i)=>i?c.lineTo(mx(p.x),mz(p.z)):c.moveTo(mx(p.x),mz(p.z)));c.stroke();c.setLineDash([]);navy.forEach(n=>{if(!n.mesh.visible)return;c.fillStyle='#ff977b';c.fillRect(mx(n.mesh.position.x)-2,mz(n.mesh.position.z)-2,4,4);});coastTowers.forEach(t=>{c.fillStyle='#8af4ec';c.fillRect(mx(t.site.x)-2,mz(t.site.z)-2,4,4);});volcanoSites.forEach(v=>{c.fillStyle='#ff8855';c.beginPath();c.moveTo(mx(v.x),mz(v.z)-4);c.lineTo(mx(v.x)-4,mz(v.z)+3);c.lineTo(mx(v.x)+4,mz(v.z)+3);c.closePath();c.fill();});c.fillStyle='#9bffd3';c.beginPath();c.arc(mx(route[route.length-1].x),mz(route[route.length-1].z),5,0,7);c.fill();c.fillStyle='white';c.save();c.translate(mx(player.position.x),mz(player.position.z));c.rotate(heading);c.beginPath();c.moveTo(0,-6);c.lineTo(-4,4);c.lineTo(4,4);c.fill();c.restore();c.fillStyle='#c9e8e3';c.font='10px Arial';c.fillText('PASSAGE CHART',13,16);c.fillText('N ↑',245,16);}
player.position.copy(route[0]);heading=1.5;const clock=new THREE.Clock();
function frame(){requestAnimationFrame(frame);const dt=Math.min(clock.getDelta(),.05);if(!paused)t+=dt;
if(!paused){for(let i=0;i<wp.count;i++){const x=wp.getX(i),z=wp.getZ(i);wp.setY(i,Math.sin(x*.055+t*1.7)*1.2+Math.sin(z*.085+t*1.3)*.7);}wp.needsUpdate=true;waterGeo.computeVertexNormals();beacons.forEach((b,i)=>{b.children[0].rotation.z=t*.5;b.children[0].position.y=14+Math.sin(t+i)*2;});repairs.forEach(r=>{r.rotation.y=t*.5;r.position.y=5+Math.sin(t*2+r.position.x);});
navy.forEach(n=>{n.mesh.position.set(n.x+Math.sin(t*.13+n.phase)*32,1,n.z+Math.cos(t*.13+n.phase)*23);n.mesh.rotation.y=-t*.13-n.phase;});aircraft.forEach((a,i)=>{a.position.set(160+Math.sin(t*.3+i*1.8)*175,52+Math.sin(t+i)*7,150+Math.cos(t*.3+i*1.8)*90);a.rotation.y=-t*.3-i*1.8;a.rotation.z=.25;});volcanoes.forEach((v,i)=>{v.craterMat.opacity=.72+.2*Math.sin(t*3.4+v.phase);v.light.intensity=2.5+1.2*Math.sin(t*3+v.phase);v.flows.forEach((f,j)=>f.material.opacity=.68+.22*Math.sin(t*2.8+j+v.phase));v.puffs.forEach((p,j)=>{const phase=(t*.12+j*.21+i*.1)%1;p.position.y=v.site.height+12+phase*82;p.position.x=Math.sin(t*.22+j*1.8+i)*8;p.position.z=Math.cos(t*.19+j*1.7+i)*7;p.material.opacity=.3*(1-phase);p.scale.setScalar(1+phase*1.3);});});coastTowers.forEach(tower=>{tower.head.rotation.y=tower.site.seaYaw+Math.sin(t*.55+tower.phase)*.22;tower.lamp.intensity=1.2+.6*Math.sin(t*2+tower.phase);});}
if(running&&!paused){time+=dt;wakeClock+=dt;if(wakeClock>.09){wakeClock=0;const w=wakes[wakeIndex++%wakes.length];w.position.set(player.position.x+Math.sin(heading)*10,1.8,player.position.z+Math.cos(heading)*10);w.scale.setScalar(.5);w.material.opacity=.45;w.visible=true;}invulnerable=Math.max(0,invulnerable-dt);shake=Math.max(0,shake-dt);const turning=(keys.a||keys.arrowleft?1:0)-(keys.d||keys.arrowright?1:0);heading+=turning*dt*1.35*(.35+speed/50);throttle=clamp(throttle+((keys.w||keys.arrowup?1:0)-(keys.s||keys.arrowdown?1:0))*dt*.5,.18,1);const boosting=keys.shift&&boost>0;boost=clamp(boost+(boosting?-23:9)*dt,0,100);const targetSpeed=keys[' ']?6:throttle*(boosting?77:46);speed+=(targetSpeed-speed)*dt*1.8;const old=player.position.clone();player.position.x-=Math.sin(heading)*speed*dt;player.position.z-=Math.cos(heading)*speed*dt;
if(lands.some(l=>inside(player.position.x,player.position.z,l.p))){player.position.copy(old);speed=4;damage(9,'SHOAL COLLISION · Turn away from shore');}player.position.x=clamp(player.position.x,-900,1100);player.position.z=clamp(player.position.z,-650,800);
const p=player.position,goal=route[leg],dist=Math.hypot(p.x-goal.x,p.z-goal.z);if(dist<29){leg++;if(leg===route.length)finish(true);}
const hormuz=p.x>-160&&p.x<45&&p.z>-165&&p.z<90,oman=p.x>=25&&p.x<360&&p.z>-25&&p.z<330;const zone=hormuz?'STRAIT OF HORMUZ / HIGH RISK':oman?'SEA OF OMAN / NAVY PATROLS':p.x<0?'PERSIAN GULF / COASTAL PASSAGE':'INDIAN OCEAN / OPEN WATER';$('zone').textContent=zone;
spawnClock+=dt;patrolClock+=dt;if(hormuz&&spawnClock>(easy?2.4:1.35)){spawnClock=0;const ahead=25+Math.random()*55;spawn(['mine','rocket','drone'][Math.floor(Math.random()*3)],p.x-Math.sin(heading)*ahead+(Math.random()-.5)*50,p.z-Math.cos(heading)*ahead+(Math.random()-.5)*50);}if(oman&&patrolClock>(easy?3.2:2)){patrolClock=0;spawn(Math.random()>.5?'rocket':'drone',p.x-Math.sin(heading)*35+(Math.random()-.5)*35,p.z-Math.cos(heading)*35+(Math.random()-.5)*35);}
navy.forEach(n=>{if(p.distanceTo(n.mesh.position)<23)damage(16,'PATROL COLLISION · Keep clear');});repairs.forEach(r=>{if(r.visible&&Math.hypot(r.position.x-p.x,r.position.z-p.z)<12){r.visible=false;hp=Math.min(100,hp+22);$('alert').textContent='REPAIR COLLECTED · +22% HULL';invulnerable=Math.max(invulnerable,.6);}});
for(const tower of coastTowers){tower.cooldown=Math.max(0,tower.cooldown-dt);if(tower.cooldown>0)continue;const index=hazards.findIndex(h=>h.type!=='mine'&&Math.hypot(h.mesh.position.x-p.x,h.mesh.position.z-p.z)<155&&Math.hypot(h.mesh.position.x-tower.site.x,h.mesh.position.z-tower.site.z)<tower.range);if(index>=0){const target=hazards[index],x=target.mesh.position.x,z=target.mesh.position.z;fireCoastTower(tower,target);burst(x,z,0x80f3eb);removeAt(hazards,index);tower.cooldown=1.45;$('alert').textContent='COAST BATTERY · '+target.type.toUpperCase()+' INTERCEPTED';}}
for(let i=hazards.length-1;i>=0;i--){const h=hazards[i];h.age+=dt;const d=Math.hypot(h.mesh.position.x-p.x,h.mesh.position.z-p.z);if(h.type==='mine'){h.mesh.position.y=Math.sin(t*3)*.8;if(d<8){damage(20,'MINE STRIKE · Hull damaged');removeAt(hazards,i);continue;}}else{h.mesh.children.slice(1).forEach(o=>o.position.y=Math.max(1,60*(1-h.age/2.5)));h.ring.scale.setScalar(1+Math.sin(h.age*13)*.1);if(h.age>=2.5){burst(h.mesh.position.x,h.mesh.position.z);if(d<(h.type==='rocket'?15:11))damage(h.type==='rocket'?24:15,h.type.toUpperCase()+' IMPACT · Evade the target rings');removeAt(hazards,i);continue;}}if(h.age>h.life)removeAt(hazards,i);}
if(invulnerable===0&&time%5<dt)$('alert').textContent=hormuz?'WARNING · Random mines, drones and rockets':oman?'Three US Navy patrols · Watch for aircraft':'';
$('hp').textContent=Math.floor(hp)+'%';$('health').style.width=hp+'%';$('health').style.background=hp<30?'#ff8156':'#7ef3be';$('boostbar').style.width=boost+'%';$('speed').textContent=Math.round(speed*.6)+' kn';$('progress').textContent=Math.min(100,Math.floor((leg-1)/8*100))+'% complete';$('clock').textContent=String(Math.floor(time/60)).padStart(2,'0')+':'+String(Math.floor(time%60)).padStart(2,'0');}
if(!paused){wakes.forEach(w=>{w.scale.addScalar(dt*2);w.material.opacity=Math.max(0,w.material.opacity-dt*.24);});for(let i=effects.length-1;i>=0;i--){const e=effects[i];e.life-=dt;e.mesh.position.addScaledVector(e.v,dt);e.v.y-=35*dt;e.mesh.scale.setScalar(Math.max(.01,e.life));if(e.life<=0)removeAt(effects,i);}}
if(!paused)for(let i=defenseShots.length-1;i>=0;i--){const shot=defenseShots[i];shot.life-=dt;shot.mesh.material.opacity=Math.max(0,shot.life/.24);if(shot.life<=0){scene.remove(shot.mesh);shot.mesh.geometry.dispose();shot.mesh.material.dispose();defenseShots.splice(i,1);}}
player.rotation.set(Math.sin(t*2)*.035,heading,Math.sin(t*2.8)*.06);player.position.y=2+Math.sin(t*2)*.6;const offset=camMode?new THREE.Vector3(0,280,150):new THREE.Vector3(Math.sin(heading)*110,83,Math.cos(heading)*110);const cp=player.position.clone().add(offset);camera.position.lerp(cp,running?.045:.012);camera.lookAt(player.position.x-Math.sin(heading)*30,0,player.position.z-Math.cos(heading)*30);if(shake>0)camera.position.x+=(Math.random()-.5)*shake*4;$('flash').style.opacity=shake*.22;minimap();renderer.render(scene,camera);}
camera.position.set(730,170,480);frame();addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});
